
development:
  adapter: postgresql
  database: drill_it_kill_it_developement
  pool: 5
  timeout: 5000
  host: localhost
  username: drillit
  password: password01

production:
  adapter: postgresql
  database: drill_it_kill_it_production
  pool: 5
  timeout: 5000

